# Change these first
owner: weallcode # Your GitHub username
repo: upptime # Your GitHub repository name

# Add your sites here
sites:
  - name: We All Code
    url: https://www.weallcode.org
  #- name: Secret Site
  #  url: $SECRET_SITE

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  #cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: ""
  navbar:
    - title: Status
      href: https://www.weallcode.org/
    #- title: GitHub
    #  href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
